// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Counter': typeof import('../components/Counter.vue')['default'],
    'InputEntry': typeof import('../components/InputEntry.vue')['default'],
    'TheFooter': typeof import('../components/TheFooter.vue')['default'],
    'TheHeader': typeof import('../components/TheHeader.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
